-- Create the Login table
CREATE TABLE Login (
    ID INT PRIMARY KEY,
    EMAIL VARCHAR(30),
    PASSWORD VARCHAR(30)
);

-- Create the Students table
CREATE TABLE Students (
    STUDENT_ID INT PRIMARY KEY,
    NAME VARCHAR(20),
    DATEOFBIRTH DATETIME,
    COUNTRY VARCHAR(40),
    MG_BALANCE MONEY,
    GENDER VARCHAR(10)
);

-- Create the Courses table
CREATE TABLE Courses (
    COURSE_NUMBER INT PRIMARY KEY,
    COURSE_CREDIT INT,
    COURSE_TITLE VARCHAR(40),
    UNIVERSITY_CODE INT FOREIGN KEY REFERENCES University(UNIVERSITY_CODE)
);

-- Create the University table
CREATE TABLE University (
    UNIVERSITY_CODE INT PRIMARY KEY,
    RANKING INT,
    FEES MONEY,
    OFFERINGS VARCHAR(40),
    FACULTY VARCHAR(30),
    STUDENT_PAYMENT VARCHAR(10),
    LOCATION VARCHAR(20),
    STUDENT_ID INT FOREIGN KEY REFERENCES Students(STUDENT_ID)
);

-- Create the Profile table
CREATE TABLE Profile (
    PROFILE_ID INT PRIMARY KEY,
    NAME VARCHAR(20),
    STUDENT_ID INT FOREIGN KEY REFERENCES Students(STUDENT_ID),
    WORK_EXPERIENCE INT,
    DEGREE VARCHAR(90),
    REGISTRATION_ID INT
);

-- Create the Major table
CREATE TABLE Major (
    MAJOR_NAME VARCHAR(20),
    STUDENT_ID INT FOREIGN KEY REFERENCES Students(STUDENT_ID)
);
