-- 1. Which University has the best ranking and what courses do they offer?
SELECT UNI.UNIVERSITY_CODE, UNI.LOCATION, UNI.RANKING, UNI.OFFERINGS
FROM UNIVERSITY AS UNI
WHERE UNI.RANKING = (SELECT MIN(RANKING) FROM UNIVERSITY);

-- 2. What are the average fees for an IT branch?
SELECT AVG(FEES) AS AVG_FEES
FROM UNIVERSITY
JOIN MAJOR ON MAJOR.STUDENT_ID = UNIVERSITY.STUDENT_ID
WHERE MAJOR_NAME = 'IT' AND OFFERINGS = 'IT';

-- 3. What are the modes of payment?
SELECT DISTINCT(STUDENT_PAYMENT)
FROM UNIVERSITY;

-- 4. What are all the universities in the AZ area and related offerings and fees?
SELECT UNIVERSITY_CODE, OFFERINGS, FEES
FROM UNIVERSITY
WHERE LOCATION = 'AZ';

-- 5. How many immigrants are having work experience more than 2 years?
SELECT COUNT(*) AS WORKEXPERIENCE_IMMIGRANTS
FROM STUDENTS
JOIN ST_PROFILE ON ST_PROFILE.STUDENT_ID = STUDENTS.STUDENT_ID
WHERE ST_PROFILE.WORK_EXPERIENCE > 2 AND STUDENTS.COUNTRY != 'USA';

